# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-15 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBj',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('asset_id', models.CharField(db_column='ASSET_ID', max_length=20, unique=True)),
                ('bams_id', models.CharField(db_column='BAMS_ID', max_length=50, unique=True)),
                ('hostname', models.CharField(db_column='HOSTNAME', db_index=True, max_length=100)),
                ('ip_addr', models.CharField(db_column='IP_ADDRESS', db_index=True, max_length=50, unique=True)),
                ('ilom_ip', models.CharField(db_column='ILOM_IP', db_index=True, max_length=50, unique=True)),
                ('device_type', models.CharField(db_column='DEVICE_TYPE', max_length=50)),
                ('is_Virtual_Instance', models.CharField(choices=[('p', 'Physical'), ('v', 'Virtual')], max_length=1)),
                ('cpu_num', models.IntegerField(db_column='CPU_No')),
                ('memory', models.IntegerField(db_column='MEMORY')),
                ('usage_catalog', models.CharField(db_column='USAGE_CATALOG', max_length=50)),
                ('os', models.CharField(db_column='OS', max_length=100)),
                ('hub_zone', models.CharField(db_column='HUB_ZONE', max_length=50)),
                ('vlan', models.CharField(db_column='VLAN', max_length=20)),
                ('comment', models.CharField(db_column='COMMENT', max_length=300)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_column='CREATED_TIME')),
                ('dataroom', models.CharField(db_column='DATAROOM', max_length=20)),
                ('row', models.IntegerField(verbose_name='ROW')),
                ('rack', models.IntegerField(verbose_name='RACK')),
                ('ru_no', models.CharField(db_column='RU_No', max_length=20)),
                ('price', models.FloatField(db_column='PRICE')),
                ('product', models.CharField(db_column='PRODUCT', max_length=50)),
                ('pdu', models.CharField(db_column='PDU', max_length=100)),
                ('vm_host', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AssetNj',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('asset_id', models.CharField(db_column='ASSET_ID', max_length=20, unique=True)),
                ('bams_id', models.CharField(db_column='BAMS_ID', max_length=50, unique=True)),
                ('hostname', models.CharField(db_column='HOSTNAME', db_index=True, max_length=100)),
                ('ip_addr', models.CharField(db_column='IP_ADDRESS', db_index=True, max_length=50, unique=True)),
                ('ilom_ip', models.CharField(db_column='ILOM_IP', db_index=True, max_length=50, unique=True)),
                ('device_type', models.CharField(db_column='DEVICE_TYPE', max_length=50)),
                ('is_Virtual_Instance', models.CharField(choices=[('p', 'Physical'), ('v', 'Virtual')], max_length=1)),
                ('cpu_num', models.IntegerField(db_column='CPU_No')),
                ('memory', models.IntegerField(db_column='MEMORY')),
                ('usage_catalog', models.CharField(db_column='USAGE_CATALOG', max_length=50)),
                ('os', models.CharField(db_column='OS', max_length=100)),
                ('hub_zone', models.CharField(db_column='HUB_ZONE', max_length=50)),
                ('vlan', models.CharField(db_column='VLAN', max_length=20)),
                ('comment', models.CharField(db_column='COMMENT', max_length=300)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_column='CREATED_TIME')),
                ('dataroom', models.CharField(db_column='DATAROOM', max_length=20)),
                ('row', models.IntegerField(verbose_name='ROW')),
                ('rack', models.IntegerField(verbose_name='RACK')),
                ('ru_no', models.CharField(db_column='RU_No', max_length=20)),
                ('price', models.FloatField(db_column='PRICE')),
                ('product', models.CharField(db_column='PRODUCT', max_length=50)),
                ('pdu', models.CharField(db_column='PDU', max_length=100)),
                ('vm_host', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AssetSh',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('asset_id', models.CharField(db_column='ASSET_ID', max_length=20, unique=True)),
                ('bams_id', models.CharField(db_column='BAMS_ID', max_length=50, unique=True)),
                ('hostname', models.CharField(db_column='HOSTNAME', db_index=True, max_length=100)),
                ('ip_addr', models.CharField(db_column='IP_ADDRESS', db_index=True, max_length=50, unique=True)),
                ('ilom_ip', models.CharField(db_column='ILOM_IP', db_index=True, max_length=50, unique=True)),
                ('device_type', models.CharField(db_column='DEVICE_TYPE', max_length=50)),
                ('is_Virtual_Instance', models.CharField(choices=[('p', 'Physical'), ('v', 'Virtual')], max_length=1)),
                ('cpu_num', models.IntegerField(db_column='CPU_No')),
                ('memory', models.IntegerField(db_column='MEMORY')),
                ('usage_catalog', models.CharField(db_column='USAGE_CATALOG', max_length=50)),
                ('os', models.CharField(db_column='OS', max_length=100)),
                ('hub_zone', models.CharField(db_column='HUB_ZONE', max_length=50)),
                ('vlan', models.CharField(db_column='VLAN', max_length=20)),
                ('comment', models.CharField(db_column='COMMENT', max_length=300)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_column='CREATED_TIME')),
                ('dataroom', models.CharField(db_column='DATAROOM', max_length=20)),
                ('row', models.IntegerField(verbose_name='ROW')),
                ('rack', models.IntegerField(verbose_name='RACK')),
                ('ru_no', models.CharField(db_column='RU_No', max_length=20)),
                ('price', models.FloatField(db_column='PRICE')),
                ('product', models.CharField(db_column='PRODUCT', max_length=50)),
                ('pdu', models.CharField(db_column='PDU', max_length=100)),
                ('vm_host', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=1)),
            ],
        ),
    ]
